config:
# others
    seed: 1234
    num_frames: 6
    mode: pixel
    offset_noise: true
    gd_type: xyz
# model related
    models:
        config: imagedream/configs/sd_v2_base_ipmv_chin8_zero_snr.yaml
        resume: release_models/ImageDream/sd-v2.1-base-4view-ipmv.pt
        resume_unet: null

# eval related
    sampler:
        target: libs.sample.ImageDreamDiffusionStage2
        params:
            mode: pixel
            num_frames: 6
            camera_views: [1, 2, 3, 4, 5, 0]
            ref_position: null
            random_background: false
            offset_noise: true
            resize_rate: 1.0

# config datasets
    train_data:
        target: libs.data.DataHQCRelative
        params:
            xyz_base: train_examples
            base_dir: train_examples
            caption_csv: train_examples/caption.csv
            image_size: 256
            repeat: 1
            camera_views: [1, 2, 3, 4, 5, 0]
            ref_indexs: [0, 1, 3, 4]
            ref_position: null
            split: train
            num_frames: 6
            random_background: true
            resize_rate: 0.95
    eval_data:
        target: libs.data.DataHQCRelative
        params:
            xyz_base: train_examples
            base_dir: train_examples
            caption_csv: train_examples/caption.csv
            image_size: 256
            repeat: 1
            camera_views: [1, 2, 3, 4, 5, 0] # when pixel mode, last image will be coverd by ref image
            ref_indexs: [0, 1, 3, 4]
            ref_position: null
            split: eval
            num_frames: 6
            random_background: true
            resize_rate: 0.95

#  optimizer related
    optimizer:
        lr: 5e-5
    gradient_accumulation_steps: 12

# wandb related parameters
    project: CRM
    wandb_run_name: CRM-xyz
    wandb_mode: offline


# training hyperparmeters
    batch_size: 16
    dataloader:
        num_workers: 10
        shuffle: true
        drop_last: true
    
    save_interval: 400000
    log_interval: 5000
    eval_interval: 50000
    max_step: 100000000
